apiVersion: v1
kind: Service
metadata:
  name: {{ include "mev-boost.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "mev-boost.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "mev-boost.selectorLabels" . | nindent 4 }}
  ports:
    - name: mev-boost
      protocol: TCP
      port: {{ .Values.port }}
      targetPort: {{ .Values.port }}
  type: ClusterIP